### ISSUE TITLE
Update the data of Hall council, Web Members etc for 2024-25

### ISSUE THREAD

**Issue by dudegladiator** [dudegladiator/azad#5]
1. Imagekit - Use this for static files instead of Uploading files inside the repository.
2. Get all the images, optimize the size and upload them on image it.io -> Get the URL and Paste it inside the code 
3. You have to get the new hall council details and add to the about page

**Comment by anuragsingh132200** [comment]
i can fix that

**Comment by dnathkoushik** [comment]
i can do it

**Comment by poonia3** [comment]
i can do it

**Comment by dudegladiator** [comment]
Deadline - 10 November 2024
